import type { PackageManager } from "../types.ts";

const RESERVED_COMMANDS: Record<PackageManager, Set<string>> = {
  npm: new Set([
    "access",
    "adduser",
    "audit",
    "bugs",
    "cache",
    "ci",
    "completion",
    "config",
    "create",
    "dedupe",
    "deprecate",
    "diff",
    "dist-tag",
    "docs",
    "doctor",
    "edit",
    "exec",
    "explain",
    "explore",
    "find-dupes",
    "fund",
    "help",
    "help-search",
    "hook",
    "i",
    "init",
    "install",
    "install-ci-test",
    "install-test",
    "link",
    "ll",
    "login",
    "logout",
    "ls",
    "org",
    "outdated",
    "owner",
    "pack",
    "ping",
    "pkg",
    "prefix",
    "profile",
    "prune",
    "publish",
    "query",
    "rebuild",
    "repo",
    "restart",
    "root",
    "search",
    "shrinkwrap",
    "star",
    "stars",
    "team",
    "token",
    "uninstall",
    "unpublish",
    "unstar",
    "update",
    "version",
    "view",
    "whoami",
  ]),
  pnpm: new Set([
    "add",
    "audit",
    "cache",
    "config",
    "create",
    "deploy",
    "dlx",
    "exec",
    "fetch",
    "help",
    "i",
    "import",
    "init",
    "install",
    "link",
    "list",
    "login",
    "logout",
    "outdated",
    "pack",
    "patch",
    "patch-commit",
    "prune",
    "publish",
    "rebuild",
    "remove",
    "root",
    "setup",
    "store",
    "unlink",
    "update",
    "why",
  ]),
  yarn: new Set([
    "add",
    "cache",
    "config",
    "constraints",
    "dedupe",
    "dlx",
    "exec",
    "explain",
    "i",
    "import",
    "info",
    "install",
    "init",
    "link",
    "node",
    "npm",
    "pack",
    "patch",
    "plugin",
    "rebuild",
    "remove",
    "set",
    "unlink",
    "up",
    "version",
    "why",
  ]),
  bun: new Set([
    "add",
    "create",
    "exec",
    "help",
    "init",
    "install",
    "link",
    "pm",
    "publish",
    "remove",
    "repl",
    "run",
    "update",
    "upgrade",
    "x",
  ]),
};

export function inferScriptName(
  packageManager: PackageManager,
  command: string,
  explicitRun: boolean,
): string | null {
  const normalizedCommand = command.trim();

  if (normalizedCommand === "") {
    return null;
  }

  if (explicitRun) {
    return normalizedCommand;
  }

  if (RESERVED_COMMANDS[packageManager].has(normalizedCommand)) {
    return null;
  }

  return normalizedCommand;
}
